version: '3'
services:
  dev:
    build: .
    volumes:
      - ./:/code
      - ./data:/data
    environment:
      - SNOWFLAKE_SOURCE_ACCOUNT_HOST
      - SNOWFLAKE_SOURCE_ACCOUNT_USERNAME
      - SNOWFLAKE_SOURCE_ACCOUNT_PASSWORD
      - SNOWFLAKE_SOURCE_ACCOUNT_WAREHOUSE
      - SNOWFLAKE_SOURCE_ACCOUNT_DATABASE
      - SNOWFLAKE_MIGRATE_ACCOUNT_HOST
      - SNOWFLAKE_MIGRATE_ACCOUNT_USERNAME
      - SNOWFLAKE_MIGRATE_ACCOUNT_PASSWORD
      - SNOWFLAKE_MIGRATE_ACCOUNT_WAREHOUSE
      - SNOWFLAKE_DESTINATION_ACCOUNT_HOST
      - SNOWFLAKE_DESTINATION_ACCOUNT_USERNAME
      - SNOWFLAKE_DESTINATION_ACCOUNT_PASSWORD
      - SNOWFLAKE_DESTINATION_ACCOUNT_WAREHOUSE

